-- 0007 — a real device list, independent of notification permission
--
-- Apply to the live D1 database with:
--   cd workers/api
--   npx wrangler d1 execute san-mes --remote --file=../migrations/0007_devices.sql --yes
--
-- WHY THE PREVIOUS ATTEMPT WAS NOT GOOD ENOUGH
--
-- The Devices screen shipped in #207 listed rows from `push_tokens`, because that was the only
-- per-device record this backend kept. Reported, correctly:
--
--   "я знаю, что на одном аккаунте может пользоваться и я, и мой друг... Но всё равно я смотрю
--    в настройках, и показывается, что только я, то есть моё устройство. Хотя это не так."
--
-- Two people share the account and the screen showed one device. That is not a mislabel that a
-- careful subtitle can fix — a device only appears in `push_tokens` if it was granted notification
-- permission and has not signed out since. A device that declined notifications is invisible, which
-- makes the screen useless for the one thing it exists to do: see who is on your account and remove
-- them. I documented that as a limitation instead of fixing it, which was the wrong call.
--
-- Recording a row at SIGN-IN is what makes the list complete, because signing in is the event the
-- feature is actually about.
--
-- WHAT AN "install_id" IS, AND WHY IT IS NOT FINGERPRINTING
--
-- `install_id` is a random v4 UUID generated by the client on first launch and kept in MMKV. It is
-- not derived from anything: not from the model, not from the OS, not from any hardware value, not
-- from a hash of any of those. It is exactly the "opaque per-install token" the compliance rules
-- name as the approved pattern, and it dies with the app's storage — reinstalling produces a new one
-- and the old row simply stops being seen.
--
-- Note in particular what it is NOT: `profiles.device_key` cannot serve this purpose even though its
-- name suggests it. That value is per-ACCOUNT — it is the login secret the second person types in to
-- get access — so both devices in the reported scenario hold the identical string.
--
-- `platform`, `model` and `os_version` exist so the owner can tell two rows apart, which is the
-- whole point of the screen ("Android" next to "Android" answers nothing). They are stored beside an
-- identifier that was already random, never combined to form one, and shown only to the account
-- holder. `app_version` is here because a stale build is the most common reason one device behaves
-- differently from another, and it costs nothing to carry.
--
-- Deliberately NOT collected: IP address, any approximation of location, carrier, advertising id,
-- screen metrics, timezone, installed-app lists, or anything else that would make this set
-- identifying rather than descriptive. `docs/privacy.html` is updated in the same change, in both
-- languages, because this is data we did not previously hold.
--
-- REVOCATION
--
-- `revoked_at` rather than a DELETE, and that distinction is load-bearing. A deleted row would be
-- recreated by the revoked device's very next heartbeat, so "disconnect" would undo itself within
-- seconds. A tombstone is what lets the server answer "you were removed" to the device that asks.
--
-- Enforcement is honest about what a stateless JWT allows. Verification in this Worker is pure HMAC
-- with zero database reads per request, and tokens last 30 days; adding a revocation lookup to that
-- path would put a D1 read on every single call. Instead the two places that already talk to the
-- database enforce it: the heartbeat tells a revoked install to sign itself out, and
-- `/v1/auth/refresh` refuses to re-issue for one, so a revoked session cannot outlive its current
-- token. A device that never reaches the network again keeps whatever it had cached until it does,
-- which is true of every token-based system and is stated in the UI rather than glossed over.

CREATE TABLE IF NOT EXISTS devices (
  -- Opaque, client-generated, random. See the note above.
  install_id   TEXT NOT NULL,
  user_id      TEXT NOT NULL,
  platform     TEXT,
  model        TEXT,
  os_version   TEXT,
  app_version  TEXT,
  first_seen_at TEXT NOT NULL,
  last_seen_at  TEXT NOT NULL,
  revoked_at    TEXT,
  -- Composite, not `install_id` alone: one physical install can sign into several accounts, and each
  -- of those is a separate row that the respective owner must be able to see and revoke
  -- independently. Keying on `install_id` alone would let a second account's sign-in overwrite the
  -- first's row, so revoking on one account would silently affect the other.
  PRIMARY KEY (install_id, user_id)
);

-- The list query: this user's devices, most recently active first.
CREATE INDEX IF NOT EXISTS idx_devices_user_seen
  ON devices (user_id, last_seen_at DESC);

-- ── TIE A PUSH TOKEN TO THE INSTALL THAT REGISTERED IT ──────────────────────
--
-- Without this, revoking a device cannot stop its notifications: `push_tokens` is keyed by the Expo
-- token and carries no way to say which install it belongs to, so the revoke would have to guess.
--
-- With it, revoking deletes that install's token row, and THAT part of revocation is immediate rather
-- than heartbeat-dependent — the push fan-out reads this table, so the revoked device stops receiving
-- messages the moment the revoke lands, whether or not it ever contacts the server again.
--
-- Nullable, and every existing row keeps NULL: those tokens were registered before this column
-- existed and there is no way to attribute them after the fact. They keep working exactly as they do
-- today (the fan-out selects by `user_id`), and each will acquire its install id the next time that
-- device registers, which happens whenever its Expo token changes or it signs in again.
ALTER TABLE push_tokens ADD COLUMN install_id TEXT;
